# Defualt configuration from GitHub

server.name: kibana
server.host: 0.0.0.0

elasticsearch.hosts: [ "http://elasticsearch:9200" ]
elasticsearch.username: elastic
elasticsearch.password: password    # Change

xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "TqaLq5U7kyeDyHN7nlamsiS3bwYwqr17" # Required for Elastic Fleet (random min. 32 char string)
xpack.fleet.agents.tlsCheckDisabled: true                                     # Required for Elastic Fleet

telemetry.optIn: false

uiSettings:
  overrides:
    "theme:darkMode": true